on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - '**'

name: Go
jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        go_version: ["1.14.9", "1.15.2"]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@722adc63f1aa60a57ec37892e133b1d319cae598
    - name: Install Go
      uses: actions/setup-go@9fbc767707c286e568c92927bbf57d76b73e0892
      with:
        go-version: ${{ matrix.go_version }}
    - name: Generate
      run: go generate ./...
    - name: Test
      run: go test ./...
    - name: Verify clean commit
      run: test -z "$(git status --porcelain)" || (git status; git diff; false)
